```{r org-chunk,message=FALSE,warning=FALSE}
#suppressWarnings(library(tidyverse))
#install.packages("usmap")
#install.packages("mapdata")
library(knitr)
library(viridis)
library(tidyverse)
library(dplyr)
library(maps)
library(stringr)
library(mapdata)
setwd("~/DataVizClass/project-1-the_tibbles")
bigfoot <- readr::read_csv('data/bigfoot.csv')
census <- readr::read_csv('data/CensusDivisions.csv')

bigfoot_xy <- bigfoot %>% select(latitude,
                                 longitude,
                                 date)
bigfoot_xy <- bigfoot_xy %>% filter(!is.na(latitude) & 
                                      !is.na(longitude) & 
                                      !is.na(date))
bigfoot_xy <- bigfoot_xy %>% mutate(date = as.integer(substring(date,
                                                                1,
                                                                4)))
usa <- map_data('usa')
state <- map_data('state')
bigfoot_xy <- bigfoot_xy %>% 
  mutate(alt_date = as.integer(substring(date,1,3))*10)
bigfoot_xy <- bigfoot_xy %>% 
  mutate(decade = paste(substring(date,1,3),"0s",
                        sep = ""))
bigfoot_xy <- bigfoot_xy %>% 
  mutate(decade=ifelse(date<1970,
                       "Pre-1970",
                       decade))
bigfoot_xy <- bigfoot_xy %>% 
  mutate(decade=ifelse(date>2009,
                       "Post-2010",
                       decade))
bigfoot_xy <- bigfoot_xy %>% 
  mutate(decade=factor(decade,
                       levels=c("Pre-1970",
                                "1970s",
                                "1980s",
                                "1990s",
                                "2000s",
                                "Post-2010")))

bigfoot_xy_mL <- bigfoot_xy %>% filter(longitude > - 125 & 
                                         longitude < -65 & 
                                         latitude > 25 & 
                                         latitude < 50)
bigfoot_xy_mL_B <- bigfoot_xy_mL %>% 
  group_by(decade) %>% 
  summarise(longitude = median(longitude),
            latitude=median(latitude))

bigfoot_xy_mL_B <- bigfoot_xy_mL_B %>%
  mutate(colour_dummy = "Median")

bigfoot_xy <- bigfoot_xy %>%
  mutate(colour_dummy = "Sighting")

cols <- c("Sighting" = "darkgreen", "Median" = "gold4")



```

```{r question-1-figure-2, fig.align="center", echo=FALSE, message=FALSE, warning = FALSE}
setwd("~/DataVizClass/project-1-the_tibbles")
bigfoot <- readr::read_csv('data/bigfoot.csv')
cols_dv <- c("West South Central" = "firebrick1", 
          "East South Central" = "firebrick3",
          "South Atlantic" = "firebrick4",
          "West North Central" = "goldenrod1",
          "East North Central" = "goldenrod3",
          "Middle Atlantic" = "seagreen4",
          "New England" = "seagreen2",
          "Pacific" = "royalblue3",
          "Mountain" = "royalblue1")
cols_rg <- c("South" = "firebrick", 
          "Northeast" = "seagreen",
          "Midwest" = "goldenrod1",
          "West" = "royalblue")
bigfoot <- bigfoot %>% filter(!is.na(date))
census <- readr::read_csv('data/CensusDivisions.csv')
census <- census %>% rename("state" = "State",
                            "region" = "Region", 
                            "division" = "Division")
bigfoot <- left_join(bigfoot,
                     census, 
                     by="state")
bigfoot_sub <- bigfoot %>% 
  select(state, 
         region, 
         division,
         date)
bigfoot_sub <- bigfoot_sub %>% 
  mutate(year = as.integer(substring(date,1,4)))
bigfoot_sub <- bigfoot_sub %>% 
  mutate(decade = paste(substring(year,1,3),"0s",
                        sep = ""))
bigfoot_sub <- bigfoot_sub %>% 
  mutate(decade=ifelse(year<1970,
                       "Pre-1970",
                       decade))
bigfoot_sub <- bigfoot_sub %>% 
  mutate(decade=ifelse(year>2009,
                       "Post-2010",
                       decade))
bigfoot_sub <- bigfoot_sub %>% 
  mutate(decade=factor(decade,
                       levels=c("Pre-1970",
                                "1970s",
                                "1980s",
                                "1990s",
                                "2000s",
                                "Post-2010")))
bigfoot_sub_rg <- bigfoot_sub %>%
  group_by(region,
           decade)%>%
  summarize(num = n())

bigfoot_sub_rg <- bigfoot_sub_rg %>% 
  mutate(region=factor(region,
                       levels=c("Northeast",
                                "Midwest",
                                "South",
                                "West")))
ggplot(data = bigfoot_sub_rg,
       mapping = aes(fill=region, 
                     y=num, 
                     x=decade)) + 
    geom_bar(position="fill",
             stat="identity")+
  scale_fill_manual(values = cols_rg,
                          name = "U.S. Census\nRegion")+
  scale_y_continuous(labels = scales::percent)+
  labs(title="Geographic distribution of Bigfoot sightings, 1869-present")+
  xlab("Decade")+
  ylab("Proportion")+
  theme_bw()

bigfoot_sub_dv <- bigfoot_sub %>%
  group_by(division,decade)%>%
  summarize(num = n())

bigfoot_sub_dv <- bigfoot_sub_dv %>% 
  mutate(division=factor(division,
                       levels=c("Middle Atlantic",
                                "New England",
                                "East North Central",
                                "West North Central",
                                "South Atlantic",
                                "East South Central",
                                "West South Central",
                                "Pacific",
                                "Mountain")))

ggplot(data = bigfoot_sub_dv,
       mapping = aes(fill=division, 
                     y=num, 
                     x=decade)) + 
    geom_bar(position="fill", 
             stat="identity")+
  scale_fill_manual(values = cols_dv,
                          name = "U.S. Census\nDivision")+
  scale_y_continuous(labels = scales::percent)+
  labs(title="Geographic distribution of U.S. Bigfoot sightings, 1869-present")+
  xlab("Decade")+
  ylab("Proportion")+
  theme_bw()

state_mp <- state %>% mutate(state=str_to_title(region))
state_mp <- left_join(state_mp, 
                      census,
                      by="state")
state_mp <- state_mp %>% 
  mutate(division=factor(division,
                       levels=c("Middle Atlantic",
                                "New England",
                                "East North Central",
                                "West North Central",
                                "South Atlantic",
                                "East South Central",
                                "West South Central",
                                "Pacific",
                                "Mountain")))

state_mp <- state_mp %>% 
  mutate(region.y=factor(region.y,
                       levels=c("Northeast",
                                "Midwest",
                                "South",
                                "West")))

ggplot()+
  geom_polygon(data=state_mp,
               aes(x=long,
                   y=lat,
                   group=group,
                   fill=region.y),
               color="black",
               alpha=1)+
  scale_fill_manual(values = cols_rg,
                          name = "U.S. Census\nRegion")+
  theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      panel.background=element_rect(fill="white"),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank())+
      scale_colour_manual(values = cols_rg,
                          name = element_blank())+
  labs(caption="Hawaii and Alaska are in the West region")+
  coord_fixed(ratio=1.3,
              xlim=c(-125,-65),
              ylim=c(25,50))

ggplot()+
  geom_polygon(data=state_mp,
               aes(x=long,
                   y=lat,
                   group=group,
                   fill=division),
               color="black",
               alpha=1)+
  scale_fill_manual(values = cols_dv,
                          name = "U.S. Census\nDivision")+
  theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      panel.background=element_rect(fill="white"),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank())+
      scale_colour_manual(values = cols_dv,
                          name = element_blank())+
  labs(caption="Hawaii and Alaska are in the Pacific division")+
  coord_fixed(ratio=1.3,
              xlim=c(-125,-65),
              ylim=c(25,50))



```

```{r question-1-figure-1-plot-1 ,fig.align="center", warning=FALSE, message=FALSE, echo = FALSE,fig.width=15, fig.height=12}
ggplot()+
  geom_polygon(data=state, #State Boundary
               aes(x=long,
                   y=lat,
                   group=group),
               color="black",
               fill=NA,
               alpha=1)+
    geom_polygon(data=usa, #National Boundary
                 aes(x=long,
                     y=lat,
                     group=group),
                 color="black",
                 fill="white",
                 alpha=0.75)+
  geom_point(data=bigfoot_xy, #All Points
             mapping=aes(x=longitude,
                         y=latitude,
                         color=colour_dummy),
             shape=18,
             alpha=0.25)+
    geom_point(data = bigfoot_xy_mL_B, #Medians
               mapping=aes(x=longitude,
                           y=latitude,
                           color=colour_dummy),
               shape=18,
               size=5)+
  coord_fixed(ratio=1.3,
              xlim=c(-125,-65),
              ylim=c(25,50))+
    facet_wrap(~  decade,
               ncol=2)+
  labs(title="Bigfoot Sightings in the Mainland United States, 1869-present",
       axis.title=element_text(size=15),
        plot.title=element_text(size=25))+
  theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      plot.title=element_text(size=20),
      panel.background=element_rect(fill="#EBEBEB"),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      legend.text=element_text(size=15),
      strip.text.x=element_text(size=15))+
      scale_colour_manual(values = cols,
                          name = element_blank())
  
```

```{r question-1-figure-1-plot-2 ,fig.align="center", warning=FALSE, message=FALSE, echo = FALSE,fig.width=15, fig.height=12}

rec_box <- data.frame(x=c(-155,-155,-55.5,-55.5,-155), 
                      y=c(10,60,60,10,10))
outline <- map("usa", 
               plot=FALSE)
outline <- data.frame(x=outline$x,
                      y=outline$y)
mask <- rbind(rec_box,
              outline)

ggplot()+
  geom_polygon(data=usa, #State Background
               aes(x=long,
                   y=lat,
                   group=group),
               color=NA,
               fill="white",
               alpha=1,
               linewidth=1)+
  geom_bin2d(data=bigfoot_xy, #Heatmap
             mapping=aes(x=longitude,
                         y=latitude),
             alpha=1,
             binwidth = c(2, 2))+
  geom_polygon(data=state, #State Boundary
               aes(x=long,
                   y=lat,
                   group=group),
               color="black",
               fill=NA,
               alpha=0.5)+
  geom_polygon(data=mask, #National Mask
               aes(x=x,y=y),
               color="#EBEBEB",
               fill="#EBEBEB",
               alpha=1)+
  geom_polygon(data=usa, #National Boundary
               aes(x=long,
                   y=lat,
                   group=group),
               color="black",
               fill=NA,
               alpha=1,
               linewidth=0.75)+
  coord_fixed(ratio=1.3,
    xlim=c(-125,-65),
              ylim=c(25,50))+
    facet_wrap(~  decade,
               ncol=2)+
  labs(title="Bigfoot Sightings in the Mainland United States, 1869-present",
       subtitle="Using 2° by 2° latitude/longitude grid")+
theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      plot.title=element_text(size=20),
      plot.subtitle=element_text(size=15),
      panel.background=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      strip.text.x=element_text(size=15))+
  scale_fill_gradientn(
    colours=c('#FFFC6B',
                       '#FF9700',
                       '#FF5B00',
                       '#E80000',
                       '#A80000',
                       '#790000'),
    limits=c(1, 100),
    name="Incidence")
  
```